/* Schedule Builder: local-first weekly planner and study-capacity engine. */
const HOUR_HEIGHT = 45, DAY_START = 6, DAY_END = 22, MIN_STUDY = 90;
const days = ['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'];
const isoDays = ['2026-08-17','2026-08-18','2026-08-19','2026-08-20','2026-08-21','2026-08-22','2026-08-23'];
const initial = { semester:{name:'Otoño 2026',start:'2026-08-17',end:'2026-12-18'}, awake:[[420,1440],[450,1440],[420,1440],[420,1440],[450,1440],[540,1440],[540,1380]], courses:[{id:'c1',name:'Algoritmos',code:'CS 301',color:'#7c71e6',prof:'Dra. Morales'},{id:'c2',name:'Física II',code:'PHY 202',color:'#1ba878',prof:'Dr. Silva'},{id:'c3',name:'Diseño',code:'DES 110',color:'#e58c3e',prof:'Ana Cruz'}], events:[{id:'e1',title:'Algoritmos',type:'Clase',course:'c1',day:0,start:540,end:630,color:'#7c71e6',before:15,after:15,repeat:'weekly'},{id:'e2',title:'Física II',type:'Clase',course:'c2',day:1,start:660,end:750,color:'#1ba878',before:15,after:15,repeat:'weekly'},{id:'e3',title:'Diseño',type:'Clase',course:'c3',day:2,start:570,end:690,color:'#e58c3e',before:0,after:0,repeat:'weekly'},{id:'e4',title:'Gym',type:'Actividad',day:0,start:1050,end:1110,color:'#ec6970',before:0,after:15,repeat:'weekly'},{id:'e5',title:'Trabajo',type:'Trabajo',day:3,start:900,end:1080,color:'#4c9dd8',before:25,after:25,repeat:'weekly'},{id:'e6',title:'Cena con amigos',type:'Ocio',day:5,start:1140,end:1260,color:'#bd70c7',before:15,after:15,repeat:'once'}], tasks:[{id:'t1',title:'Problem set 2',course:'c1',deadline:'2026-08-21',startDate:'2026-08-17',minutes:240,priority:'Alta',progress:25,type:'Problem set'},{id:'t2',title:'Capítulo 5',course:'c2',deadline:'2026-08-20',startDate:'2026-08-17',minutes:150,priority:'Media',progress:0,type:'Reading'},{id:'t3',title:'Moodboard',course:'c3',deadline:'2026-08-23',startDate:'2026-08-18',minutes:180,priority:'Media',progress:40,type:'Project'}] };
let data = JSON.parse(localStorage.getItem('schedule-builder-v1') || 'null') || initial;
let modal = null, drag = null;
const $ = s => document.querySelector(s);
const time = m => `${String(Math.floor(m/60)%24).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
const duration = m => `${Math.floor(m/60)}h${m%60?` ${m%60}m`:''}`;
const clamp = (v,a,b) => Math.max(a,Math.min(b,v));
function persist(){ localStorage.setItem('schedule-builder-v1',JSON.stringify(data)); }
function merge(intervals){ const out=[]; intervals.sort((a,b)=>a[0]-b[0]).forEach(x=>{let last=out[out.length-1]; if(last&&x[0]<=last[1])last[1]=Math.max(last[1],x[1]);else out.push([...x])}); return out; }
function dayBlocks(day){ const [awakeStart,awakeEnd]=data.awake[day]; const busy=data.events.filter(e=>e.day===day).map(e=>[Math.max(awakeStart,e.start-(e.before||0)),Math.min(awakeEnd,e.end+(e.after||0))]).filter(x=>x[1]>x[0]); let cursor=awakeStart, blocks=[]; merge(busy).forEach(([s,e])=>{if(s>cursor&&s-cursor>=MIN_STUDY)blocks.push([cursor,s]);cursor=Math.max(cursor,e)});if(awakeEnd-cursor>=MIN_STUDY)blocks.push([cursor,awakeEnd]);return blocks; }
function available(from=0,to=6){return Array.from({length:to-from+1},(_,i)=>dayBlocks(from+i)).flat().reduce((n,[s,e])=>n+e-s,0)}
function taskNeeded(task){return Math.round(task.minutes*(1-task.progress/100))}
function deadlineDay(task){const n=Math.round((new Date(task.deadline+'T12:00')-new Date(isoDays[0]+'T12:00'))/86400000);return clamp(n,0,6)}
function taskCapacity(task){const start=clamp(Math.ceil((new Date(task.startDate+'T12:00')-new Date(isoDays[0]+'T12:00'))/86400000),0,6);return available(start,deadlineDay(task))}
function summary(){const needed=data.tasks.reduce((n,t)=>n+taskNeeded(t),0), avail=available(), cushion=avail-needed;return {needed,avail,cushion};}
function render(){const s=summary(); $('#app').innerHTML=`<div class="app"><aside class="sidebar"><div class="brand">Schedule <span>Builder</span></div><div class="semester"><small>SEMESTRE ACTIVO</small><b>${data.semester.name}</b><small>${data.semester.start} - ${data.semester.end}</small></div><nav class="nav"><button class="active"><span class="icon">▦</span>Calendario</button><button onclick="openTask()"><span class="icon">✓</span>Tareas <small>${data.tasks.length}</small></button><button onclick="openCourse()"><span class="icon">◉</span>Cursos</button><button onclick="openAwake()"><span class="icon">◷</span>Awake Time</button></nav><div><div class="section-title">CURSOS</div><div class="course-list">${data.courses.map(c=>`<div class="course"><i class="dot" style="background:${c.color}"></i>${c.name}<small>${c.code}</small></div>`).join('')}<button class="new-link" onclick="openCourse()">+ Añadir curso</button></div></div><footer>⌘ K para acciones rápidas</footer></aside><main class="workspace"><header class="topbar"><div><div class="crumb">Planificador / Semana actual</div><h1>Tu semana</h1></div><div class="top-actions"><button class="button" onclick="openTask()">+ Tarea</button><button class="button primary" onclick="openEvent()">+ Evento</button></div></header><section class="calendar-card"><div class="calendar-head"><div class="week-label">Semana 1 <small>17 - 23 de agosto, 2026</small></div><div class="calendar-actions"><button class="button" onclick="openAwake()">◷ Awake time</button><div class="week-nav"><button>‹</button><button>›</button></div></div></div><div class="days"><div class="time-head">Hora</div>${days.map((d,i)=>`<div class="day-head ${i===0?'today':''}"><b>${d}</b><span>${new Date(isoDays[i]+'T12:00').getDate()} Ago</span></div>`).join('')}</div><div class="calendar-body"><div class="time-axis">${Array.from({length:17},(_,i)=>`<span style="top:${i*HOUR_HEIGHT}px">${String(DAY_START+i).padStart(2,'0')}:00</span>`).join('')}</div><div class="grid">${days.map((_,d)=>dayColumn(d)).join('')}</div></div><div class="legend"><span><i style="background:#7274e9"></i>Study Time automático</span><span><i style="background:#dfe3eb"></i>Sleep</span><span><i style="background:#91a0b8"></i>Commute</span></div></section></main><aside class="rightbar">${rightbar(s)}</aside></div>${modal||''}<div id="toast" class="toast hidden"></div>`; }
function pos(m){return (m-DAY_START*60)/60*HOUR_HEIGHT}
function dayColumn(d){const [a,b]=data.awake[d], blocks=dayBlocks(d);return `<div class="day-col" data-day="${d}" onpointerdown="startNew(event,${d})"><div class="sleep" style="top:0;height:${Math.max(0,pos(a))}px"></div><div class="sleep" style="top:${pos(b)}px;bottom:0"></div>${blocks.map(([s,e])=>`<div class="study-block" style="top:${pos(s)}px;height:${pos(e)-pos(s)}px">Study Time<br>${time(s)} - ${time(e)}</div>`).join('')}${data.events.filter(e=>e.day===d).map(eventHTML).join('')}</div>`}
function eventHTML(e){const top=pos(e.start), height=Math.max(21,pos(e.end)-top), ct=Math.max(0,pos(e.start-(e.before||0))), ch=(e.before||0)/60*HOUR_HEIGHT+(e.after||0)/60*HOUR_HEIGHT+height;return `<div class="commute" style="top:${ct}px;height:${ch}px"></div><div class="event" data-id="${e.id}" style="top:${top}px;height:${height}px;border-color:${e.color};background:${e.color}20" onpointerdown="startDrag(event,'${e.id}')" ondblclick="openEvent('${e.id}')"><b>${e.title}</b><small>${time(e.start)} - ${time(e.end)}</small><i class="resize" onpointerdown="startResize(event,'${e.id}')"></i></div>`}
function rightbar(s){const status=s.cushion<0?'Overloaded':s.cushion<180?'Tight':'On Track', cls=s.cushion<0?'bad':s.cushion<180?'over':'';return `<h2>Resumen de estudio</h2><div class="status ${cls}"><strong>${status==='On Track'?'✓ ':status==='Tight'?'⚠ ':'⚠ '}${status}</strong><small>${status==='On Track'?'Tu semana tiene margen suficiente.':status==='Tight'?'Hay poco margen antes de tus deadlines.':'Las tareas superan tu capacidad semanal.'}</small></div><div class="metric-grid"><div class="metric"><label>Disponible</label><b>${duration(s.avail)}</b></div><div class="metric"><label>Necesario</label><b>${duration(s.needed)}</b></div><div class="metric"><label>Cushion</label><b class="${s.cushion>=0?'positive':'negative'}">${s.cushion>=0?'+':''}${duration(s.cushion)}</b></div><div class="metric"><label>Bloques</label><b>${Array.from({length:7},(_,i)=>dayBlocks(i).length).reduce((a,b)=>a+b,0)}</b></div></div><div class="panel"><div class="panel-title">Carga por día <button onclick="openAwake()">Editar</button></div>${days.slice(0,5).map((d,i)=>{const a=available(i,i),p=Math.min(100,Math.round(a/720*100));return `<div class="deadline"><b>${d} <small>${duration(a)} disponibles</small></b><div class="load"><i style="width:${p}%"></i></div></div>`}).join('')}</div><div class="panel"><div class="panel-title">Próximos deadlines <button onclick="openTask()">Ver tareas</button></div>${[...data.tasks].sort((a,b)=>a.deadline.localeCompare(b.deadline)).slice(0,4).map(t=>{const cap=taskCapacity(t), n=taskNeeded(t);return `<div class="deadline"><time>${t.deadline.slice(5).split('-').reverse().join('/')}</time><b>${t.title}</b><small>${duration(n)} restante · ${cap>=n?'en tiempo':'sin capacidad'}</small></div>`}).join('')}</div></aside>`}
function notify(text){const el=$('#toast');el.textContent=text;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),1800)}
function closeModal(){modal=null;render()} function field(label,key,type='text',value='',full=false,opts=''){return `<label class="${full?'full':''}">${label}${type==='select'?`<select name="${key}">${opts}</select>`:`<input required name="${key}" type="${type}" value="${value}">`}</label>`}
function openEvent(id){const e=data.events.find(x=>x.id===id)||{title:'',type:'Actividad',day:0,start:600,end:660,color:'#5a5be7',before:0,after:0,repeat:'weekly'};modal=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><form class="modal" onsubmit="saveEvent(event,'${id||''}')"><h2>${id?'Editar evento':'Nuevo evento'}</h2><div class="form">${field('Nombre','title','text',e.title,true)}${field('Día','day','select','',false,days.map((x,i)=>`<option value="${i}" ${e.day===i?'selected':''}>${x}</option>`).join(''))}${field('Tipo','type','select','',false,['Clase','Actividad','Trabajo','Comida','Ocio','Viaje'].map(x=>`<option ${e.type===x?'selected':''}>${x}</option>`).join(''))}${field('Inicio','start','time',time(e.start))}${field('Fin','end','time',time(e.end))}${field('Commute antes (min)','before','number',e.before)}${field('Commute después (min)','after','number',e.after)}${field('Color','color','color',e.color)}${field('Repetir','repeat','select','',false,['weekly','once'].map(x=>`<option ${e.repeat===x?'selected':''} value="${x}">${x==='weekly'?'Semanal':'Solo esta semana'}</option>`).join(''))}</div><div class="modal-actions">${id?'<button class="button danger" type="button" onclick="deleteEvent(\''+id+'\')">Eliminar</button>':'<span></span>'}<div><button class="button" type="button" onclick="closeModal()">Cancelar</button><button class="button primary">Guardar</button></div></div></form></div>`;render()}
function saveEvent(ev,id){ev.preventDefault();const f=new FormData(ev.target), get=k=>f.get(k);const obj={id:id||crypto.randomUUID(),title:get('title'),type:get('type'),day:+get('day'),start:parseTime(get('start')),end:parseTime(get('end')),before:+get('before'),after:+get('after'),color:get('color'),repeat:get('repeat')};if(obj.end<=obj.start)return notify('La hora final debe ser posterior');if(id)data.events=data.events.map(x=>x.id===id?obj:x);else data.events.push(obj);persist();closeModal();notify('Evento guardado y bloques recalculados')}
function deleteEvent(id){data.events=data.events.filter(e=>e.id!==id);persist();closeModal();notify('Evento eliminado')}
function parseTime(v){const [h,m]=v.split(':').map(Number);return h*60+m}
function openTask(){const list=data.tasks.map(t=>`<div class="deadline"><time>${t.deadline}</time><b>${t.title}</b><small>${duration(taskNeeded(t))} restante · capacidad ${duration(taskCapacity(t))}</small></div>`).join('');modal=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>Tareas</h2><div class="panel">${list}</div><button class="button primary" onclick="newTask()">+ Nueva tarea</button><button class="button" onclick="closeModal()" style="float:right">Cerrar</button></div></div>`;render()}
function newTask(){const courses=data.courses.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');modal=`<div class="modal-backdrop"><form class="modal" onsubmit="saveTask(event)"><h2>Nueva tarea</h2><div class="form">${field('Nombre','title','text','',true)}${field('Curso','course','select','',false,courses)}${field('Tipo','type','select','',false,'Problem set,Reading,Exam,Project,Essay'.split(',').map(x=>`<option>${x}</option>`).join(''))}${field('Inicio','startDate','date','2026-08-17')}${field('Deadline','deadline','date','2026-08-23')}${field('Duración estimada (min)','minutes','number','120')}${field('Prioridad','priority','select','',false,'Alta,Media,Baja'.split(',').map(x=>`<option>${x}</option>`).join(''))}</div><div class="modal-actions"><span></span><div><button type="button" class="button" onclick="openTask()">Cancelar</button><button class="button primary">Guardar</button></div></div></form></div>`;render()}
function saveTask(ev){ev.preventDefault();const f=new FormData(ev.target);data.tasks.push({id:crypto.randomUUID(),title:f.get('title'),course:f.get('course'),type:f.get('type'),startDate:f.get('startDate'),deadline:f.get('deadline'),minutes:+f.get('minutes'),priority:f.get('priority'),progress:0});persist();closeModal();notify('Tarea añadida; capacidad actualizada')}
function openCourse(){modal=`<div class="modal-backdrop"><form class="modal" onsubmit="saveCourse(event)"><h2>Nuevo curso</h2><div class="form">${field('Nombre','name','text','',true)}${field('Código','code','text','')}${field('Profesor','prof','text','')}${field('Color','color','color','#5a5be7')}</div><div class="modal-actions"><span></span><div><button type="button" class="button" onclick="closeModal()">Cancelar</button><button class="button primary">Guardar</button></div></div></form></div>`;render()}
function saveCourse(ev){ev.preventDefault();const f=new FormData(ev.target);data.courses.push({id:crypto.randomUUID(),name:f.get('name'),code:f.get('code'),prof:f.get('prof'),color:f.get('color')});persist();closeModal();notify('Curso añadido')}
function openAwake(){modal=`<div class="modal-backdrop"><form class="modal" onsubmit="saveAwake(event)"><h2>Awake Time</h2><p class="muted">Solo estos intervalos cuentan para estudio. Fuera de ellos se muestra sueño.</p><div class="form">${days.map((d,i)=>`${field(d+' inicio','s'+i,'time',time(data.awake[i][0]))}${field(d+' fin','e'+i,'time',time(data.awake[i][1]))}`).join('')}</div><div class="modal-actions"><span></span><div><button type="button" class="button" onclick="closeModal()">Cancelar</button><button class="button primary">Guardar</button></div></div></form></div>`;render()}
function saveAwake(ev){ev.preventDefault();const f=new FormData(ev.target);data.awake=days.map((_,i)=>[parseTime(f.get('s'+i)),parseTime(f.get('e'+i))]);persist();closeModal();notify('Awake Time actualizado')}
function startDrag(e,id){if(e.target.classList.contains('resize'))return; e.stopPropagation();drag={mode:'move',id,originY:e.clientY,base:data.events.find(x=>x.id===id).start};e.currentTarget.setPointerCapture?.(e.pointerId)}
function startResize(e,id){e.stopPropagation();drag={mode:'resize',id,originY:e.clientY,base:data.events.find(x=>x.id===id).end};e.currentTarget.parentElement.setPointerCapture?.(e.pointerId)}
function startNew(e,day){if(e.target!==e.currentTarget)return; const rect=e.currentTarget.getBoundingClientRect(), mins=clamp(Math.round(((e.clientY-rect.top)/HOUR_HEIGHT*60+DAY_START*60)/15)*15,DAY_START*60,DAY_END*60-30);openEvent();setTimeout(()=>{const d=document.querySelector('[name=day]'),s=document.querySelector('[name=start]'),en=document.querySelector('[name=end]'); if(d)d.value=day;if(s)s.value=time(mins);if(en)en.value=time(mins+60)},0)}
window.addEventListener('pointermove',e=>{if(!drag)return;const ev=data.events.find(x=>x.id===drag.id),delta=Math.round((e.clientY-drag.originY)/HOUR_HEIGHT*60/15)*15;if(drag.mode==='move'){const len=ev.end-ev.start;ev.start=clamp(drag.base+delta,DAY_START*60,DAY_END*60-len);ev.end=ev.start+len}else ev.end=clamp(drag.base+delta,ev.start+30,DAY_END*60);render()});window.addEventListener('pointerup',()=>{if(drag){persist();drag=null;notify('Horario actualizado') }});
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal)closeModal();if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openEvent()}});render();
