/* Bridge legacy modal actions into the unified renderer. */
window.closeModal = () => { modal = null; unified.render(); };
window.openEvent = (eid='') => {
  const e = data.events.find(x=>x.id===eid) || {title:'',courseId:'',day:0,start:600,end:660,color:'#5a5be7',before:0,after:0,repeat:'weekly'};
  const opts = `<option value="">Sin curso</option>${data.courses.map(c=>`<option value="${c.id}" ${c.id===e.courseId?'selected':''}>${c.name}</option>`).join('')}`;
  modal = `<div class="modal-backdrop"><form class="modal" onsubmit="saveUnifiedEvent(event,'${eid}')"><h2>${eid?'Editar evento':'Nuevo evento'}</h2><div class="form">${field('Nombre','title','text',e.title,true)}${field('Día','day','select','',false,days.map((d,i)=>`<option value="${i}" ${i===e.day?'selected':''}>${d}</option>`).join(''))}${field('Curso','courseId','select','',false,opts)}${field('Inicio','start','time',time(e.start))}${field('Fin','end','time',time(e.end))}${field('Commute antes','before','number',e.before)}${field('Commute después','after','number',e.after)}${field('Color','color','color',e.color)}${field('Repetir','repeat','select','',false,['once','weekly','biweekly'].map(x=>`<option ${x===e.repeat?'selected':''}>${x}</option>`).join(''))}</div><div class="modal-actions"><span></span><div><button class="button" type="button" onclick="closeModal()">Cancelar</button><button class="button primary">Guardar</button></div></div></form></div>`;
  unified.render();
};
window.saveUnifiedEvent = (ev,eid) => { ev.preventDefault(); const f=new FormData(ev.target), g=k=>f.get(k), x={id:eid||crypto.randomUUID(),title:g('title'),courseId:g('courseId'),day:+g('day'),start:parseTime(g('start')),end:parseTime(g('end')),before:+g('before'),after:+g('after'),color:g('color'),repeat:g('repeat')}; if(x.end<=x.start){toast('La hora final debe ser posterior');return;} if(eid)data.events=data.events.map(e=>e.id===eid?x:e);else data.events.push(x);persist();modal=null;unified.render();toast('Evento guardado; bloques recalculados'); };
window.openAwake = () => { modal=`<div class="modal-backdrop"><form class="modal" onsubmit="saveUnifiedAwake(event)"><h2>Awake Time</h2><p class="muted">Solo estos intervalos cuentan como tiempo potencial de estudio.</p><div class="form">${days.map((d,i)=>`${field(d+' inicio','s'+i,'time',time(data.awake[i][0]))}${field(d+' fin','e'+i,'time',time(data.awake[i][1]))}`).join('')}</div><div class="modal-actions"><span></span><div><button class="button" type="button" onclick="closeModal()">Cancelar</button><button class="button primary">Guardar</button></div></div></form></div>`;unified.render(); };
window.saveUnifiedAwake = ev => {ev.preventDefault();let f=new FormData(ev.target);data.awake=days.map((_,i)=>[parseTime(f.get('s'+i)),parseTime(f.get('e'+i))]);persist();modal=null;unified.render();toast('Awake Time actualizado');};
